os: linux

dist: bionic

language: cpp

git:
  submodules: false

branches:
  except:
    - gh-pages

cache:
  directories:
    - "$HOME/.nimble"
    - "$HOME/.choosenim"

matrix:
  include:
    - os: linux
      env:
        - CHOOSENIM_CHOOSE_VERSION=1.2.4
    - os: linux
      env:
        - CHOOSENIM_CHOOSE_VERSION=stable
    - os: linux
      env:
        - CHOOSENIM_CHOOSE_VERSION=devel
    - os: osx
      env:
        - CHOOSENIM_CHOOSE_VERSION=stable

install:
  - |
      curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
      sh init.sh -y

before_script:
  - |
      set -ex
      export CHOOSENIM_NO_ANALYTICS=1
      export PATH=$HOME/.nimble/bin:$PATH

script:
  - nim -v
  - nimble test
  - |
    # examples timeout in 1.2.4
    if [ "v$CHOOSENIM_CHOOSE_VERSION" != "v1.2.4" ]; then
      nimble examples
    fi
