os: linux

dist: bionic

language: cpp

branches:
  except:
    - gh-pages

cache:
  directories:
    - "$HOME/.nimble"
    - "$HOME/.choosenim"

matrix:
  include:
    - os: linux
    - os: linux
      env: TEST_CPP=1

install:
  - |
      curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
      sh init.sh -y

before_script:
  - |
      set -ex
      export CHOOSENIM_NO_ANALYTICS=1
      export PATH=$HOME/.nimble/bin:$PATH

script:
  - |
    nim -v;
    [ $TEST_CPP == 1 ] \
      && nimble testcpp \
      || nimble test;
