os: linux

dist: bionic

language: cpp

git:
  submodules: false

branches:
  except:
    - gh-pages

cache:
  directories:
    - "$HOME/.nimble"
    - "$HOME/.choosenim"

matrix:
  include:

    - os: linux
      arch: amd64
      env:
        - NIM_VERSION=1.2.4
    - os: linux
      arch: amd64
      env:
        - NIM_VERSION=stable
    - os: linux
      arch: amd64
      env:
        - NIM_VERSION=devel

    - os: linux
      arch: arm64
      env:
        - NIM_VERSION=1.2.4
    - os: linux
      arch: arm64
      env:
        - NIM_VERSION=stable
    - os: linux
      arch: arm64
      env:
        - NIM_VERSION=devel

    - os: linux
      arch: ppc64le
      env:
        - NIM_VERSION=1.2.4
    - os: linux
      arch: ppc64le
      env:
        - NIM_VERSION=stable
    - os: linux
      arch: ppc64le
      env:
        - NIM_VERSION=devel

    - os: linux
      arch: s390x
      env:
        - NIM_VERSION=1.2.4
    - os: linux
      arch: s390x
      env:
        - NIM_VERSION=stable
    - os: linux
      arch: s390x
      env:
        - NIM_VERSION=devel

    - os: osx
      env:
        - NIM_VERSION=1.2.4
    - os: osx
      env:
        - NIM_VERSION=stable
    - os: osx
      env:
        - NIM_VERSION=devel

install:
  - uname -m
  - |
      case $TRAVIS_CPU_ARCH in
        amd64 )
          export CHOOSENIM_CHOOSE_VERSION=$NIM_VERSION
          export CHOOSENIM_NO_ANALYTICS=1
          pushd ~
          curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
          sh init.sh -y
          popd
          ;;
        * )
          case $NIM_VERSION in
            stable )
              ref=`git ls-remote https://github.com/nim-lang/Nim.git | grep refs/tags | tail -n 2 | head -n 1 | sed 's/^.*tags\///'`
              ;;
            devel )
              ref=devel
              ;;
            * )
              ref="v$NIM_VERSION"
              ;;
          esac
          pushd ~
          git clone -b $ref --single-branch https://github.com/nim-lang/Nim.git
          pushd Nim
          sh build_all.sh
          popd
          popd
          ;;
      esac

before_script:
  - |
      set -ex
      export PATH=$HOME/.nimble/bin:$HOME/Nim/bin:$PATH

script:
  - nim -v
  - nimble test
  - |
    # examples timeout in 1.2.4
    if [ "v$NIM_VERSION" != "v1.2.4" ]; then
      nimble examples
    fi
