name: Build
on:
  pull_request:
    paths-ignore:
      - README.md
  push:
    paths-ignore:
      - README.md

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test_x86:
    name: Test nim-${{ matrix.nim-version }} / ${{ matrix.runs-on }} / x86_64
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: macos-latest
            nim-version: 1.4.2
          - runs-on: ubuntu-latest
            nim-version: 1.2.8

    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Disable tcp/udp offloading
        run: |
          # Prevent network slowness
          # See https://github.com/actions/virtual-environments/issues/1187#issuecomment-696195756
          # and https://github.com/enso-org/enso/pull/1159
          if [ "${{ runner.os }}" == "macOS" ]; then
            sudo sysctl -w net.link.generic.system.hwcksum_tx=0
            sudo sysctl -w net.link.generic.system.hwcksum_rx=0
          else
            sudo ethtool -K eth0 tx off rx off
          fi

      # Optimization: re-use cached Nim->C compilation
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ${HOME}/.cache
          key: cache-${{ matrix.runs-on }}-${{ matrix.nim-version }}

      - name: Checkout Nim project
        uses: actions/checkout@v2

      - name: Install asdf
        uses: asdf-vm/actions/setup@v1.1.0

      - name: Install asdf-nim
        run: |
          git clone https://github.com/asdf-community/asdf-nim.git "${HOME}/asdf-nim" --branch main --depth 1
          asdf plugin add nim "${HOME}/asdf-nim"
          asdf nim install-deps -y

      - name: Install Nim
        run: |
          set -uexo pipefail
          asdf install nim ${{ matrix.nim-version }}
          asdf local nim ${{ matrix.nim-version }}

      - name: Run tests
        run: |
          nimble develop -y
          nimble test
          nimble examples

  test_non_x86:
    name: Test nim-${{ matrix.nim-version }} / debian-buster / ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Test on non-x86 Linux using run-on-arch-action
          - nim-version: 1.4.2
            arch: armv7
          - nim-version: 1.2.8
            arch: aarch64
          - nim-version: 1.4.2
            arch: ppc64le

    runs-on: ubuntu-latest
    steps:
      - name: Disable tcp/udp offloading
        run: |
          # Prevent network slowness
          # See https://github.com/actions/virtual-environments/issues/1187#issuecomment-696195756
          # and https://github.com/enso-org/enso/pull/1159
          if [ "${{ runner.os }}" == "macOS" ]; then
            sudo sysctl -w net.link.generic.system.hwcksum_tx=0
            sudo sysctl -w net.link.generic.system.hwcksum_rx=0
          else
            sudo ethtool -K eth0 tx off rx off
          fi

      # Optimization: re-use cached Nim->C compilation
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ${HOME}/.cache
          key: cache-${{ matrix.arch }}-${{ matrix.nim-version }}

      - name: Checkout Nim project
        uses: actions/checkout@v2

      # Install & run tests on non-x86
      - uses: uraimo/run-on-arch-action@v2.0.8
        name: Install Nim & run tests
        with:
          arch: ${{ matrix.arch }}
          distro: buster

          dockerRunArgs: |
            --volume "${HOME}/.cache:/root/.cache"

          setup: mkdir -p "${HOME}/.cache"

          shell: /usr/bin/env bash

          install: |
            set -uexo pipefail
            # Install asdf and dependencies
            apt-get update -q -y
            apt-get -qq install -y build-essential curl git
            git clone https://github.com/asdf-vm/asdf.git "${HOME}/.asdf" --branch v0.8.0

          env: |
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          run: |
            set -uexo pipefail
            . "${HOME}/.asdf/asdf.sh"

            env

            # Install asdf-nim and dependencies
            git clone https://github.com/asdf-community/asdf-nim.git ~/asdf-nim --branch main --depth 1
            asdf plugin add nim ~/asdf-nim
            asdf nim install-deps -y

            # Install Nim
            asdf install nim ${{ matrix.nim-version }}
            asdf local nim ${{ matrix.nim-version }}

            # Run tests
            nimble develop -y
            nimble test
            nimble examples
