name: Build
on:
  pull_request:
    paths-ignore:
      - README.md
  push:
    paths-ignore:
      - README.md
  schedule:
    - cron: "0 0 * * *" # daily at midnight

jobs:
  build:
    name: Test nim-${{ matrix.nim-version }} / ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-latest
            nim-version: latest
          - runs-on: macos-latest
            nim-version: latest

    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout Nim project
        uses: actions/checkout@v2

      - name: Install asdf
        uses: asdf-vm/actions/setup@v1

      - name: Install asdf-nim
        run: |
          git clone \
            --branch main --depth 1
            https://github.com/asdf-community/asdf-nim.git \
            "${HOME}/asdf-nim
          asdf plugin add nim "${HOME}/asdf-nim"
          asdf nim install-deps -y

      - name: Install Nim
        run: |
          asdf install nim ${{ matrix.nim-version }}
          asdf local nim ${{ matrix.nim-version }}

      - name: Run tests
        run: |
          nimble develop -y
          nimble test
          nimble examples
