# yamllint disable rule:line-length
# yamllint disable rule:comments

name: Build
on:
  pull_request:
    paths-ignore:
      - README.md
  push:
    paths-ignore:
      - README.md
  schedule:
    - cron: '0 0 * * *' # daily at midnight

jobs:
  build:
    name: Test nim-${{ matrix.nim-version }} / ${{ matrix.runs-on }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-latest
            nim-version: latest
          - runs-on: macos-latest
            nim-version: latest

    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Install nim
        uses: asdf-vm/actions/plugins-add@v1
        with:
          tool_versions: |
            nim ${{ matrix.nim-version }}

      - name: Run tests
        run: |
          nimble develop -y
          nimble test
          nimble examples
